name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.MY_DOCKER_PWD }}" | \
          docker login -u "${{ secrets['MY_DOCKER_USERNAME'] }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets['MY_DOCKER_USERNAME'] }}/cicd-demo:latest .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets['MY_DOCKER_USERNAME'] }}/cicd-demo:latest
